import Provider from '@/components/Providers'
import './globals.css'


export const metadata = {
  title: 'Chat App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {children}    
        </Provider>
      </body>
    </html>
  )
}
